### ISSUE TITLE
Is there necessity to forecast price based on other Independent variables? 

### ISSUE THREAD

**Issue by harkar1978** [fritzfritzfritzz/EES_Optimisation#17]
Anticipated energy consumption is derived out of past consumption data applied with certain statistical values to forecast for future period. However, main element to control the Electricity market is Price. Unlike Goods, Electricity must be produced at the same time it is consumed, with the exception of Storage of electricity in Batteries, which happens in short scale. Therefore, Price fluctuates throughout the day. Wholesale weighted Electricity price (day-ahead price on exchange) is determined on Day-ahead auction that takes place in previous day [source: ENTSO-E]

* Long term contracts - future trading - Hedging
* Day-ahead trading - Previous day
* Intra day spot market - Only electricity output is traded

In the Spot market, which installation ultimately produces electricity is determined by Merit order in auctions - listing of installations by the price quoted for generation of Electricity. Price is not fixed until entire Electricity demand has been fully met. It is determined by the installation with highest marginal cost. This price is good for other producers , because they get the same price and thus higher rate of return. 

Since all this happens in Day-ahead trading on daily basis, there is no requirement to forecast price, since the objective is to use solar energy surplus (surplus energy generated over own consumption) either to generate additional revenue by selling to the power grid or to store it for own consumption during peak price prevailing during the day

**Comment by AnnaWey** [comment]
We decided for now not to predict the price and focus only on consumption and generation
