### ISSUE TITLE
Suggested approach to Optimisation using Reinforcement learning

### ISSUE THREAD

**Issue by harkar1978** [fritzfritzfritzz/EES_Optimisation#19]
to use solar energy surplus (surplus energy generated over own consumption) either to generate additional revenue by selling to the power grid or to store it for own consumption during peak price prevailing during the day. In that case, things that would be compared are 1. revenue per MW hour of surplus energy sold to grid, 2. Solar energy stored in battery and used during peak hours of the day, thereby saving in Peak hour Electricity price during the day, 3. No storage (minimum saving would be electricity consumed to charge the batteries)

**Comment by wanchainagel** [comment]
Decided to try out different approaches. Each one will evaluated in performance and quality.

1) Simple Q-Learning (Wanchai)

2) Linear Programming (Fritz)

3) Deep Q-Learning (Fritz?)
